# Desativa DDL automático do Hibernate
quarkus.hibernate-orm.database.generation=none

# Habilita o Flyway
quarkus.flyway.migrate-at-start=true

# Desativa as credenciais fixas no código (o Dev Services cuida disso em modo dev/test)
quarkus.datasource.db-kind=postgresql